
services:
  # Laravel application (Backend)
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: paysoko_app
    env_file:
      - .env
    volumes:
       - ./backend:/var/www
    working_dir: /var/www
    networks:
      - app-network
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_KEY=${APP_KEY}
      - CACHE_DRIVER=${CACHE_DRIVER}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_PASSWORD}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
      - redis

  # Next.js frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: paysoko_frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - ./frontend/.env.local
    stdin_open: true
    tty: true
    depends_on:
      - app

  # MySQL database
  db:
    image: mysql:8
    container_name: mysql_db
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

  # Redis cache
  redis:
    image: redis:6.2
    container_name: redis_cache
    restart: always
    networks:
      - app-network

  # Nginx reverse proxy
  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./backend:/var/www
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - app
      - frontend

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
