services:
  # Laravel application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paysoko_app
    volumes:
      - .:/var/www
    networks:
      - app-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=ecommerce
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
      - redis

  # React frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: paysoko_frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost/api
    stdin_open: true
    tty: true

  # MySQL database
  db:
    image: mysql:8
    container_name: mysql_db
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - app-network

  # Redis cache
  redis:
    image: redis:6.2
    container_name: redis_cache
    restart: always
    networks:
      - app-network

  # Nginx reverse proxy
  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/var/www
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - app
      - frontend

networks:
  app-network:

volumes:
  dbdata:
