name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           echo "Host droplet" >> ~/.ssh/config
           echo "  HostName ${{ secrets.DROPLET_IP }}" >> ~/.ssh/config  # Ensure you replace with correct IP
           echo "  User root" >> ~/.ssh/config  # Replace 'root' if you are using a different user
           echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
           echo "  StrictHostKeyChecking no" >> ~/.ssh/config  # Automatically accept host key

      - name: Add SSH key to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
          
      - name: Deploy application
        run: |
          ssh droplet 'cd /path/to/app && git pull && docker-compose up -d --build'
