name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH keys for accessing the DigitalOcean droplet
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host droplet" >> ~/.ssh/config
          echo "  HostName ${{ secrets.DROPLET_IP }}" >> ~/.ssh/config
          echo "  User root" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config

      # Add the DigitalOcean Droplet to the known hosts
      - name: Add droplet to known hosts
        run: ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      # Deploy to DigitalOcean Droplet
      - name: Deploy app to DigitalOcean
        run: |
          ssh droplet << 'EOF'
            # Ensure Docker and Docker Compose are installed
            if ! command -v docker &> /dev/null; then
              echo "Docker not found, installing Docker..."
              apt-get update && apt-get install -y docker.io
            fi

            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose not found, installing Docker Compose..."
              curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              chmod +x /usr/local/bin/docker-compose
            fi

            # Set up the app directory on the Droplet
            if [ ! -d "/home/paysoko.app/.git" ]; then
              echo "Cloning repository into /home/paysoko.app..."
              rm -rf /home/paysoko.app
              git clone https://github.com/omusegad/Paysoko-commerce.git /home/paysoko.app
            else
              echo "Repository exists, pulling latest changes..."
              cd /home/paysoko.app && git pull origin main
            fi

            # Build and run the containers using Docker Compose
            echo "Starting application using Docker Compose..."
            cd /home/paysoko.app && docker-compose -f /home/paysoko.app/docker-compose.yml up -d --build
          EOF
